name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select test ro run
        required: true
        type: choise
        default: all
        options:
          - all


jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Setup python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
        
